[project]
name = 'Tokenized-Healthcare-Precision-Diagnostics'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.patient-verification]
path = 'contracts/patient-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.result-verification]
path = 'contracts/result-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.test-protocol]
path = 'contracts/test-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.treatment-recommendation]
path = 'contracts/treatment-recommendation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
